### ISSUE TITLE
Nothing in outputs for input 640x480, after long time... 24GB VRAM

### ISSUE THREAD

**Issue by zelenooki87** [csslc/CCSR#1]
Hi. Thank you for wonderful project. I was able to evaluate model on Windows. but only for images <320x240

I have RTX 3090 24GB VRam gpu. 
Is it expected to be such a slow and without results (Real world model)?
Do you recommend try code in Ubuntu? 
thank you

**Comment by csslc** [comment]
Hi, thanks for your interest in our work!
Because of the limited GPU memory, our inference code is mainly to perform 4x super-resolution of 128->512.
It seems your problem is because the size of the input image is larger than 128. A larger input image size costs more GPU memory and may slow down the inference time.
You can use the tiling function by modifying 'tiled' from 'store_true' to 'store_false' in 'inference_ccsr.py', and see if that resolves your issue.
Using this function further slows down the inference time and may introduce border artifacts, but is more GPU memory-friendly.

**Comment by csslc** [comment]
Hi, thanks for your interest in our work!
In our inference code of 'inference_ccsr.py', the input is resized to 512 by default. Under the default settings, the size of the input image should not be affected. Could you provide more information, such as the error message when running the code?

**Comment by zelenooki87** [comment]
That was because of Out of memory. Can we use your model tiled? please advice

**Comment by csslc** [comment]
You can use the tiling function by modifying the 'tiled' from 'store_true' to 'store_false' in 'inference_ccsr.py'. You can also choose appropriate 'tile_size' and 'tile_stride' according to your GPU memory and running time. However, more border artifacts may be introduced in this function.
